"""Add recommendations column to TestResult

Revision ID: 784e09434a0c
Revises: 
Create Date: 2025-03-22 22:58:43.899935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '784e09434a0c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recommendations', sa.Text(), nullable=True))
        batch_op.drop_column('general_recommendation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('general_recommendation', sa.TEXT(), nullable=False))
        batch_op.drop_column('recommendations')

    # ### end Alembic commands ###
